# loftus
Base URL: https://www.loftusrecreationcentre.com.au/
This knowledge base combines official pricing/schedules from OneNote with current website content.
Last updated: Auto-generated from multiple sources

---
## Official Information (Pricing, Schedules, Contact)
*Source: Internal OneNote documentation*
## Contact Info

Wednesday, June 21, 2023 3:23PM

MeganSaggers(CentreManager)-msaggers@belgravialeisure.com.au NetaniTalemaitoga(SportsManager)-loftussports@belgravialeisure.com.au NOJUNIORSPORTS ANYMORE

DannieZappulla(ProgramsCoordinator)-loftusprograms@belgravialeisure.com.au

Tara Enoka(HealthClub Coordinator)-tenoka@belgravialeisure.com.au General-loftusreception@belgravialeisure.com.au

BookingRequests-loftusbookings@belgravialeisure.com.au

## Opening Hours

Wednesday,June21,2023 3:07 PM

Mondayto Friday 5:45am-9:00pm Saturday8:00 am-6:00pm Sunday8:30am-5:30pm

ANZACDay 12pm-6pm No classes

## Social Sports

Thursday,January 30,2025 9:55AM

## SPORTS

- 2 seasons per year
- O September- March (Summer)
- OMarch-September(Winter)
- Allsportsrunintheeveningsunlessotherwisestated
- All leagues are opentoanymixofgenders unless otherwise stated
- ·Teamregistrationsremainopenallseasonprovided there'sspaceinthecompetition
- ·Various grades available for all sports, potential participants can see which grades have space via each sport'sregistrationpage

## Basketball

Mens - Mondays + Wednesdays Womens - Mondays Mixed - Sundays

## Netball

Mixed - Tuesdays(PM) + Thursdays(PM)

Ladies - Tuesdays(PM) + Thursdays(AM+PM)

## Futsal

Loftus indoor (5-a-side) - Wednesdays Dorrien Gardens (separate venue) outdoor (6-a-side) - Mondays + Wednesdays Plans to begin a mixed league on a Wednesday evening at Dorrien Gardens, expressions of interest accepted

## IndoorVolleyball

Tuesdays

## Rebound Soccer

Loftus indoor (5-a-side) - Monday

## FEES

## Game fees

Basketball/Volleyball/Loftus soccer-$76 Dorrien Gardensfutsal-$80 Netball -$80

Forfeit fees ForfeitFee(Morethan48hours'notice):Gamefee ForfeitFee(Lessthan48hours'notice):Gamefee+$15 Forfeit Fee(Less than 1hours'notice/No-show):Gamefee+$40 Withdrawalfee:$115

Important dates for upcoming season

## 2025Winter SeasonImportant Dates

Summer Semi Finals &amp; Winter Grading 17th-23rd March

## Summer Grand Finals &amp; Winter Grading

24th-30thMarch

## 2025WinterSeasonCommences

31st March - 6th April

## Winter Semi Finals &amp; Summer Grading

8th - 14th September

## Winter Grand Finals &amp; Summer Grading

15th-21stSeptember

## Reformer Pilates &amp; Timetable

Wednesday,July 03,2024

2:32PM

Loftusreformerpilatesisnowhere!

ReformerisavailabletoFitnessPassportHoldersatthereducedrateof$35.95

## REFORMERPILATES TIMETABLE

OCTOBER2024

|         | MONDAY        | TUESDAY         | WEDNESDAY     | THURSDAY       | FRIDAY          | SATURDAY         | SUNDAY   |
|---------|---------------|-----------------|---------------|----------------|-----------------|------------------|----------|
| 6:00am  | REFORMER Ally |                 | REFORMER Ally |                | REFORMER Jackie |                  |          |
| 7:30am  |               |                 |               |                |                 | REFORMER Sherina |          |
| 8:30am  | REFORMER Ally | REFORMER Nicole | REFORMER Ally | REFORMER Libby | REFORMER Libby  | REFORMER Sherina |          |
| 9:30am  | REFORMER Ally | REFORMER Nicole | REFORMER Ally | REFORMER Libby | REFORMER Libby  | REFORMER Mya     |          |
| 10:30am |               |                 |               |                |                 | REFORMER Mya     |          |

| 4:30pm   | REFORMER Ally   |               | REFORMER Mya   |               | REFORMER Claire   |
|----------|-----------------|---------------|----------------|---------------|-------------------|
| 5:30pm   | REFORMER Ally   | REFORMER Sara | REFORMER Mya   | REFORMER Sara |                   |

recreationcentre

| Casual Visits               | Cost   |
|-----------------------------|--------|
| Day pass gym                | $21.00 |
| Casual Group Fitness        | $19.00 |
| Casual Seniors Program      | $11    |
| 10 Visit Group Fitness Pass | $180   |
| 20 VisitGroupFitness Pass   | $340   |
| 10 Visit Gym Pass           | $195   |
| 20 Visit Gym Pass           | $360   |

## Memberships

Wednesday, June 21, 2023 3:23 PM

Loftus Recreation Centre has both'Full Access' and ‘Premium'memberships available.

All memberships include:

- ·24/7Access
- ·Group Fitness (Les Mills, Freestyle and Yoga)
- ·FreeCreche
- ·Casual use of courts(subject to availability)

| MembershipType               | Adult Price                                                                             | Conc Price                                                                 | Included                                                                                                                                                                                                                                                                 | Notes                                                                                                                                                                                                                                                                                                                                    |
|------------------------------|-----------------------------------------------------------------------------------------|----------------------------------------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Premier Membership           | $49.95 P/W $99 Joining Fee                                                              | $39.95 P/W (over 55s) $99 Joining Fee                                      | ·MZ-3 heart rate monitor (More info here: https://www.loftusrecrea tioncentre.com.au/train/ myzone) ·Functional Training classes ·Reformer Pilates ·Group Fitness Classes (https://www.loftusrecre ationcentre.com.au/train /timetables) ·24/7 Health Club Access ·Begin | Free suspension ·7 days' notice to upgrade/downgrade between memberships ·30days'notice tocancel                                                                                                                                                                                                                                         |
| Premier Membership- 12 month | $39.95 P/W $99 Joining Fee                                                              | N/A                                                                        | As above                                                                                                                                                                                                                                                                 | ·12monthminimum term ·Free suspension ·7days'notice to upgrade/downgrade ·30 days' notice to cancel                                                                                                                                                                                                                                      |
| Flexi Membership             | $20.50 P/W $60 Joining Fee                                                              | $19.00 P/W (students) $60Joining Fee $16.40 P/W (over 55s) $60 Joining Fee | ·24/7 Health Club Access ·Group Fitness Classes (https://www.loftusrecre ationcentre.com.au/train /timetables) ·Begin                                                                                                                                                    | ·$5per week suspension fee ·30 days'notice to cancel                                                                                                                                                                                                                                                                                     |
| TeenFit Membership           | $16.40 P/W $60 Joining Fee (13-15yo only)                                               |                                                                            | ·No 24/7 access - only during staffed hours ·No group fitness ·Begin (they must complete the first appointment priorto using the gym on their own) ·Strongly recommended to only engage in workouts according to program prescribed by their Begin trainer               | ·$5 per week suspension fee ·30 days'notice to cancel                                                                                                                                                                                                                                                                                    |
| Full Access  FIFO ONLY       | 2:1 FIFO Roster $7.50 P/W $60 Joining Fee or 1:1 FIFO Roster $11.00 P/W $60 Joining Fee |                                                                            | ·24/7 Health Club Access ·Group Fitness Classes (https://www.loftusrecre ationcentre.com.au/train /timetables) ·Begin                                                                                                                                                    | ·Proof of roster (such as a letter from employer) must be provided upon request or the membership will revert to the applicable standard rate. ·The available rates ($7.50 or $10.00 P/w willbe dependent on the roster supplied. ·Membership only available in-centre.Please contact directly to arrange a tour and to join at facility |

·Direct Debit options for PT available.Please refer customer to venue for sale of PT membership.

## Fitness Passport

Friday, July 18, 2025 8:15 AM

- ·Gym access
- ·Courtaccess-ifavailable

Noreformerpilatesorfunctional trainingonFP

FP members wishing to upgrade to premium will be $35.95.This will maintain consistency for reporting.

Will alsoneedtoincludethatwhentheFPmembercomesin,theywillneedtostillscantheirFB membership card

## Court Availability

Monday,August05,2024 2:00 PM

Customers/Guests are free to visit the centre and try their luck with using oneofthecourts,however:

- Most of the year they have large user groups booked all weekend, and they typically occupy all of the courts.
- ·Asageneral rule,before3:30pmonaweekdaywould usuallybeasafebet,buttheyalso occasionallyhaveaschool/schoolsbookoutallofthecourtsforabasketballcarnivalor something similar.
- ·They also(especially duringwinter),havethelocal TAFEcert3/4sports studentscome down andbookoutcourtsad-hoc.

If Customers/Guests enquire about court availability,pleaselet themknow of these conditions anddirectthemtocontactthecentreviathephonenumber:0892276526

If they come through to CC, transfer them to centre.Current transfer number is 0439205320 * *(as of 05/08/2024)

## $8 for casual shooting

## Group Fitness

Wednesday,June21,2023

3:23PM

## Loftus' group fitness timetable canbe found here:

https://www.loftusrecreationcentre.com.au/train/timetables

The timetable can change seasonally, so it's best to view online for the most up to date version.

Virtual classes(RPM/Sprint) are available as timetabled options, or on-demand. Our cycle studio has a projector and screen that can stream videos filmed by Les Mills, where instructorswillrunthroughtheRPMandSprintclassesthemembersknowandlove. hoursprovided they don'tclashwithapreexistingclass.Videoscanbeselectedviaa tabletmounted

These are on our group fitness timetable, but can also be selected at any time during our staffed on thewall in the cycle studio-just askstaff toshow you how.

## Trials

Wednesday, June 21, 2023 3:23PM

Loftus offers 1-day trials for regular gym access.

1 class trial availablefor Reformerand Functional Training Classes

## Creche

## Loftus has closed its creche permanently as of April 2024

## Public Holiday Updates

Wednesday,June21,2023 3:24PM

Loftus is closed completely on New Year's Day, Good Friday, Christmas Day and Boxing Day. On all other public holidays our opening hours are 9am-6pm. Members can of course still access the gym 24/7, 365 days a year.

PleasecheckourwebsiteandFacebookpageformoreinformation.

## Concessions

Wednesday,June21,2023 3:25PM

Loftus accepts all valid forms of concession card.Seniors/healthcare/disability pension cards. We also accept Companion cards for carers coming in to utilise the facilities with their clients.

---
## Website Content (Facilities, Programs, Current Information)
*Source: Website crawl - 10 pages*
### Available Pages:
1. https://www.loftusrecreationcentre.com.au/
2. https://www.loftusrecreationcentre.com.au/venue/active-world
3. https://www.loftusrecreationcentre.com.au/footer-links/inclusive-activities
4. https://www.loftusrecreationcentre.com.au/join/loftus-memberships
5. https://www.loftusrecreationcentre.com.au/train/reformer-pilates-(1)
6. https://www.loftusrecreationcentre.com.au/junior/school-holiday-activities
7. https://www.loftusrecreationcentre.com.au/train/begin-program
8. https://www.loftusrecreationcentre.com.au/train/memberships-passes
9. https://www.loftusrecreationcentre.com.au/play/inclusive-activities
10. https://www.loftusrecreationcentre.com.au/join/member-benefits

# loftus

Base URL: https://www.loftusrecreationcentre.com.au/

Total pages crawled: 10

---

## Page 1: https://www.loftusrecreationcentre.com.au/

[](/)

[ 08 9227 6526 ](tel:08 9227 6526)

[ Membership ](https://www.loftusrecreationcentre.com.au:443/join/loftus-memberships) [ Free Trial ](https://www.loftusrecreationcentre.com.au:443/join/1-day-free-trial)

  * Junior

    * [ School Holiday Program ](/junior/school-holiday-activities)
Close 

  * Train

    * [ Reformer Pilates ](/train/reformer-pilates-\(1\))
    * [ B Active Functional Training ](/train/b-active-functional-training)
    * [ Memberships at Loftus ](/train/memberships-passes)
    * [ Fitness Facilities ](/train/fitness-facilities)
    * [ BEGIN Program ](/train/begin-program)
    * [ Personal Training ](/train/personal-training)
    * [ Group Exercise Classes ](/train/group-fitness-classes)
    * [ Timetables ](/train/timetables)
    * [ MyZone ](/train/myzone)
    * [ Seniors Exercise Program ](/train/sep)
    * [ Take Charge! Program ](/train/take-charge-program)
    * [ Member Benefits ](/train/member-benefits)
Close 

  * Sports

    * [ Social Sport Competitions ](/play/competitions)
    * [ Basketball ](/play/basketball)
    * [ Netball ](/play/netball)
    * [ Indoor and Outdoor Futsal ](/play/futsal)
    * [ Rebound Soccer ](/play/rebound-soccer)
    * [ Volleyball ](/play/volleyball)
    * [ Court Hire ](/play/court-hire)
    * [ Inclusive Activities ](/play/inclusive-activities)
Close 

  * Venue

    * [ News/Blog ](/venue/news-blog)
    * [ What's On ](/venue/whats-on)
    * [ Cafe ](/venue/cafe)
    * [ Telehealth ](/venue/tele-health)
    * [ Physiotherapy ](/venue/exercise-physiology)
    * [ Room Hire ](/venue/room-hire)
    * [ Timetables ](/venue/timetables)
    * [ FAQs ](/venue/faqs)
    * [ About Us ](/venue/about-us)
    * [ Your Membership App ](/venue/active-world)
Close 

  * Join

    * [ Member Benefits ](/join/member-benefits)
    * [ Memberships at Loftus ](/join/loftus-memberships)
    * [ Claim Your Free Trial ](/join/1-day-free-trial)
Close 

  * Contact Us

    * [ Customer Service Charter ](/contact-us/customer-service-charter)
    * [ Get in Touch ](/contact-us/get-in-touch)
    * [ Getting to Loftus Recreation Centre ](/contact-us/location)
    * [ Employment ](/contact-us/employment)
    * [ Manage My Membership ](/contact-us/manage-membership)
    * [ Membership Enquiry ](/contact-us/membership-enquiry)
Close 

  * Search 

Search

Search 




  * [ ](/)
  * Home 



# Home

## 

[ Learn More ](/train/reformer-pilates-\(1\))

## 

[ Learn More ](https://www.loftusrecreationcentre.com.au/train/b-active-functional-training)

## 

[ Learn More ](https://www.loftusrecreationcentre.com.au/train/begin-program)

## Health Club

We strive to provide a diverse and affordable range of quality health and fitness programs to all members of our community in a safe, friendly and fun environment.

[ Learn More ](/train/fitness-facilities) [ 24/7 Induction ](https://docs.google.com/forms/d/1UI_fTD_xwahPa2LAww95Mz7llmiLh1XzQ5PSPf5oRXE/viewform?ts=5f55c6ca&edit_requested=true)

## Begin Program 

Is the complimentary program designed with you in mind - providing the perfect introduction to our health club, tailored to suit beginners and experienced gym-goers alike.

[ Learn More ](/train/programs)

## Sport Courts

Loftus has 4 huge indoor mulitpurpose courts and 1 sparkling new outdoor AstroTurf soccer court.

[ Learn More ](/play/court-hire)

## 

## **Welcome to Loftus Recreation Centre**

Loftus Recreation Centre is a multipurpose sporting and fitness facility located in Leederville, Western Australia.  
  
Loftus is a hub for the Leederville community that for the past 30 years has, and continues to, provide health and fitness solutions, sporting facilities, and community access. We are one of the largest leisure facilities in the state with something for everyone to enjoy.  
  
We are home to a 760sqm 24/7 gym, group fitness and reformer pilates studios, cycling studios, and so much more! [To find out more, please click here.](https://www.loftusrecreationcentre.com.au/train/memberships-passes)

  
We offer various social sports competitions in both junior and senior leagues. If you've ever wanted to play social netball, indoor/outdoor futsal, rebound soccer, volleyball, pickleball, or basketball, Loftus is the place to be. These are spread out across different days through the week and multiple time slots are available to suit everyone. [To find out more, please click here.](https://www.loftusrecreationcentre.com.au/play/competitions)  
  
We also offer various style rooms to hire for functions, birthdays, meetings, etc. [To find out more, please click here.](https://www.loftusrecreationcentre.com.au/venue/room-hire)

**Come in and visit us today, we look forward to providing you with the best health and leisure experiences possible!**

### Centre Opening Hours

##### Monday - Thursday  
6:00 AM - 10:30 PM

##### Friday  
6:00 AM - 9:30 PM

##### Saturday  
7:00 AM - 9:00 PM

##### Sunday  
7:00 AM - 8:00 PM

  
Please keep up to date with us on our Facebook page and via our member emails. If you are not receiving our emails, please click [here](https://www.loftusrecreationcentre.com.au/contact-us/get-in-touch) to subscribe and get the latest updates.

### Discover Loftus Recreation Centre

Take your first steps with a Free Trial and see what Loftus Recreation Centre has to offer you.

[ Free Trial ](/join/1-day-free-trial) [ Member Benefits ](/train/member-benefits)

##  Latest News [ VIEW ALL NEWS ](/landing-pages/blog-news)

10 Oct 25 

###  World Mental Health Day! 

World Mental Health Day is observed on 10 October each year as a global movement to raise awareness, reduce stigma, and encourage positive action for mental wellbeing. The day invites communities, workplaces, schools, and individuals to pause, reflect, and act in ways that strengthen social connection and mental health.  


[ Read more ](/news/world-mental-health-day)

01 Sep 25 

###  Say Yes to You: Make Time to Move 

It's Women’s Health Week 2025! Whether small or bold, every choice to move supports your physical, mental, and social wellbeing. Read more about the health tips to follow this week from our Group Health and Wellbeing Manager, Victoria Goodwin-Barlow, and our Allied Health Manager, Kia Naylor.  


[ Read More ](/news/say-yes-to-you-make-time-to-move)

04 Aug 25 

###  Loneliness Awareness Week 2025 

Loneliness Awareness Week, from Ending Loneliness Together, shines a spotlight on the shared experience of loneliness and calls on all Australians, including individuals, communities, workplaces, education, and government, to take action to reduce loneliness and create more opportunities for meaningful social connections

[ Read More ](/news/loneliness-awareness-week-2025)

14 Jun 25 

###  How you can embrace active wellbeing this Global Wellness Day 

Our individual health and wellbeing are paramount to enjoying a fulfilled life alongside our loved ones, engaging in countless valuable experiences to remember. This Global Wellness Day, we’re taking a closer look at how being more active, no matter your circumstance or ability, can positively boost your health and enjoyment of life. 

[ Read More ](/news/how-you-can-embrace-active-wellbeing-this-global-w)

### 24/7 Gym Access

Work out on your own time! Loftus Recreation caters for all members of the community with multiple bonuses to a membership. Come and see what all the fuss is about!

[ Learn More ](/train/fitness-facilities)

### Children's Sport 

Loftus Recreation Centre runs Junior Clinics for Basketball, Netball and Soccer during each school term, and break for school holidays.

[ Learn More ](/play/childrens-sports)

### TripAdvisor Panel

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut quis fermentum dolor, in mollis lacus. Morbi pulvinar sem tortor, aliquet suscipit erat sollicitudin sed. Nulla ultricies convallis ipsum, ac semper sapien sollicitudin non. Vestibulum lobortis turpis purus, sed rutrum dolor mattis in. Aenean dapibus pellentesque nisi in convallis. Nulla a sapien tincidunt, convallis nunc vitae, iaculis lectus. Integer pellentesque venenatis pellentesque. Quisque vel pellentesque diam. In accumsan accumsan risus et porta. Aliquam a quam ut enim facilisis gravida. Aenean finibus metus justo, scelerisque euismod metus semper vitae. Phasellus non risus libero.

  * [About Us](/footer-links/about-us)
  * [Customer Service Charter](/footer-links/customer-service-charter)
  * [Inclusive Activities](/footer-links/inclusive-activities)
  * [FAQs](/footer-links/faqs)
  * [Employment](/footer-links/employment)
  * [Memberships](/footer-links/memberships)
  * [Blog/News](/footer-links/blog-news)
  * [Events](/footer-links/events)
  * [Privacy Policy](/footer-links/privacy-policy)



###  Contact us 

  * 99 Loftus Street, Leederville - 6007 
  * 08 9227 6526 


  * [ ](https://www.instagram.com/loftusrec)
  * [ ](https://www.facebook.com/LoftusRec)
  * [ ](https://www.youtube.com/channel/UC4MKxP96QCfcxfyBWCsc33A)



[ ](https://www.belgraviafoundation.org.au/our-purpose) [ ](http://www.companioncard.org.au/)

[Proudly managed by Belgravia Leisure](https://belgravialeisure.com.au)


---

## Page 2: https://www.loftusrecreationcentre.com.au/venue/active-world

[](/)

[ 08 9227 6526 ](tel:08 9227 6526)

[ Membership ](https://www.loftusrecreationcentre.com.au:443/join/loftus-memberships) [ Free Trial ](https://www.loftusrecreationcentre.com.au:443/join/1-day-free-trial)

  * Junior

    * [ School Holiday Program ](/junior/school-holiday-activities)
Close 

  * Train

    * [ Reformer Pilates ](/train/reformer-pilates-\(1\))
    * [ B Active Functional Training ](/train/b-active-functional-training)
    * [ Memberships at Loftus ](/train/memberships-passes)
    * [ Fitness Facilities ](/train/fitness-facilities)
    * [ BEGIN Program ](/train/begin-program)
    * [ Personal Training ](/train/personal-training)
    * [ Group Exercise Classes ](/train/group-fitness-classes)
    * [ Timetables ](/train/timetables)
    * [ MyZone ](/train/myzone)
    * [ Seniors Exercise Program ](/train/sep)
    * [ Take Charge! Program ](/train/take-charge-program)
    * [ Member Benefits ](/train/member-benefits)
Close 

  * Sports

    * [ Social Sport Competitions ](/play/competitions)
    * [ Basketball ](/play/basketball)
    * [ Netball ](/play/netball)
    * [ Indoor and Outdoor Futsal ](/play/futsal)
    * [ Rebound Soccer ](/play/rebound-soccer)
    * [ Volleyball ](/play/volleyball)
    * [ Court Hire ](/play/court-hire)
    * [ Inclusive Activities ](/play/inclusive-activities)
Close 

  * Venue

    * [ News/Blog ](/venue/news-blog)
    * [ What's On ](/venue/whats-on)
    * [ Cafe ](/venue/cafe)
    * [ Telehealth ](/venue/tele-health)
    * [ Physiotherapy ](/venue/exercise-physiology)
    * [ Room Hire ](/venue/room-hire)
    * [ Timetables ](/venue/timetables)
    * [ FAQs ](/venue/faqs)
    * [ About Us ](/venue/about-us)
    * [ Your Membership App ](/venue/active-world)
Close 

  * Join

    * [ Member Benefits ](/join/member-benefits)
    * [ Memberships at Loftus ](/join/loftus-memberships)
    * [ Claim Your Free Trial ](/join/1-day-free-trial)
Close 

  * Contact Us

    * [ Customer Service Charter ](/contact-us/customer-service-charter)
    * [ Get in Touch ](/contact-us/get-in-touch)
    * [ Getting to Loftus Recreation Centre ](/contact-us/location)
    * [ Employment ](/contact-us/employment)
    * [ Manage My Membership ](/contact-us/manage-membership)
    * [ Membership Enquiry ](/contact-us/membership-enquiry)
Close 

  * Search 

Search

Search 




  * [ ](/)
  * Venue
  * Your Membership App 



# Your Membership App

**Active World Logo Update**

Our membership portal, Active World, has a new look! Your app now has a new logo, but there are no changes to the way you use it. 

## 

We believe all our members health & fitness journey should be powered by innovative technology. The Active World app was specifically designed to improve your experience with us! The app will give you greater control of your membership and our programs offered in Centre! 

The Active World app allows you to link your family memberships to manage from the once account and will give you greater visibility of your progress and achievements when visiting us! 

Our staff are here to help! Active World is built to improve communication with our team – so if you need us, we are a click of a button away to start chatting! 

Download the app today to get started and bring your membership into the palm of your hand! 

## 

  
Your Active World self-managed portal will allow you to: 

  * Manage your account details 

  * Update your payment details 

  * Check for your next payment 

  * Buy a new membership 

  * Buy a visit pass 

  * Scan in using a digital access card – for when you forget your pass! 

  * Book into your Group Fitness Classes 

  * View upcoming classes 

  * Send and receive messages to the Centre staff 




What our short video on all the things Active World will allow you to do! 

  
Download the app to login or sign up - use the code **LOFTUS**

[Download the app](http://qrco.de/bbRx0F)

## 

### GET STARTED AS AN EXISITING MEMBER 

As an existing member, we have set you up using the email you provided us upon joining – **all you have to do is reset your password!**

If you are currently using Active World for your GOswim lessons – all you need to do is update the app! 

1\. [Download ](http://qrco.de/bbRx0F)the Active World App 

2\. Use the facility code **LOFTUS**

3\. Select **forgot password** to reset your account – follow the prompts 

4\. Login once ready and create your quick access code – 4 digits 

5\. Now you're in! Check your programs or book into a new class! 

  
Watch this quick video on how to set up your app 

### GET STARTED AS A NEW MEMBER 

Looking to join our community! WELCOME! 

It's super easy to get you started! 

1\. [Download ](http://qrco.de/bbRx0F)the Active World App and select Sign Up  
  
2\. Use the facility code **LOFTUS**

3\. Create your quick access code – 4 digits 

4\. Now you're in! 

5\. Click Buy Membership - Select your preference 

6\. Follow the prompts to get started! 

For more information about specific memberships or class bookings see our FAQs below. 

Watch this quick video on how to join! 

## 

[DOWNLOAD THE APP NOW](http://qrco.de/bbRx0F)

##  Frequently Asked Questions Expand all 

#####  Does the App work on iPhones and Android? 

Yes, it sure does! You can download the Active World App from the App Store or the Google Store.

[Download App ](http://qrco.de/bbRx0F)

If you are using a different device, you can login to your portal view the web link here https://blau.activeworld.com.au/

#####  I am creating an account, but it says an account already exists. 

If you are already a member with us, we have set you up using the email you provided us upon joining – all you have to do is reset your password!

This means once you reset your password and login all your membership information will be ready for you to check!

#####  My children’s memberships are not showing in my account. 

If you have multiple memberships with us in the centre – this could be yourself and your children, you should be able to see them within your account. If you cannot, please talk to our team next time you are in the centre or message us on the app to check the email address you have used to login is the primary email on all your memberships. If your child is not currently a member, you can sign them up in the app.

#####  Can I add my partner or a relative to my account? 

Yes, you can! From the home screen of the app, click on the 3 lines in the top left-hand corner (next to our centre logo). This will bring up the task bar on the left of your screen. Now select “MY RELATIVES” - you are able to view, add or remove relatives. Once added to your profile, the relative can download the app onto their phone and login using the same information on the relative profile (the email address you used). They will be able to see everything except personal details and account information

#####  How do I contact the centre on the app? 

We have made sure that we are only the click of a button away should you need to contact us! All you have to do is select “MESSENGER” from the home screen or the task bar to chat with our team.

#####  How do I update my billing details? 

We understand billing details need to be easy to update and change! So, we have made it simple! From the home screen of the app, click on the 3 lines in the top left-hand corner (next to our centre logo). This will bring up the task bar on the left of your screen. Select “MY BILLING DETAILS” scroll down to 'My Billing Details'. Select “EDIT” at the top of any section you wish to update your details in – don't forget to hit SAVE!

#####  My email address has changed, how do I update it? 

Login to your app and update your email address on your personal profile page.

#####  Is the app free? 

It sure is!

#####  I just changed my class day/time however the app has our original day/time listed. 

The App and Active World sync in live time. If your class day is showing incorrectly in your schedule, please contact the centre to ensure you are booked into the correct class.

#####  My App doesn’t show the update. 

Anyone with an IOS (Apple) you just need to update your device.

If you don't have auto update selected Go to APP Store -> Click Today (Bottom Left Hand Side) -> Click your profile pic (top right hand side) -> scroll down to active world app and click update.

### TripAdvisor Panel

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut quis fermentum dolor, in mollis lacus. Morbi pulvinar sem tortor, aliquet suscipit erat sollicitudin sed. Nulla ultricies convallis ipsum, ac semper sapien sollicitudin non. Vestibulum lobortis turpis purus, sed rutrum dolor mattis in. Aenean dapibus pellentesque nisi in convallis. Nulla a sapien tincidunt, convallis nunc vitae, iaculis lectus. Integer pellentesque venenatis pellentesque. Quisque vel pellentesque diam. In accumsan accumsan risus et porta. Aliquam a quam ut enim facilisis gravida. Aenean finibus metus justo, scelerisque euismod metus semper vitae. Phasellus non risus libero.

  * [About Us](/footer-links/about-us)
  * [Customer Service Charter](/footer-links/customer-service-charter)
  * [Inclusive Activities](/footer-links/inclusive-activities)
  * [FAQs](/footer-links/faqs)
  * [Employment](/footer-links/employment)
  * [Memberships](/footer-links/memberships)
  * [Blog/News](/footer-links/blog-news)
  * [Events](/footer-links/events)
  * [Privacy Policy](/footer-links/privacy-policy)



###  Contact us 

  * 99 Loftus Street, Leederville - 6007 
  * 08 9227 6526 


  * [ ](https://www.instagram.com/loftusrec)
  * [ ](https://www.facebook.com/LoftusRec)
  * [ ](https://www.youtube.com/channel/UC4MKxP96QCfcxfyBWCsc33A)



[ ](https://www.belgraviafoundation.org.au/our-purpose) [ ](http://www.companioncard.org.au/)

[Proudly managed by Belgravia Leisure](https://belgravialeisure.com.au)


---

## Page 3: https://www.loftusrecreationcentre.com.au/footer-links/inclusive-activities

[](/)

[ 08 9227 6526 ](tel:08 9227 6526)

[ Membership ](https://www.loftusrecreationcentre.com.au:443/join/loftus-memberships) [ Free Trial ](https://www.loftusrecreationcentre.com.au:443/join/1-day-free-trial)

  * Junior

    * [ School Holiday Program ](/junior/school-holiday-activities)
Close 

  * Train

    * [ Reformer Pilates ](/train/reformer-pilates-\(1\))
    * [ B Active Functional Training ](/train/b-active-functional-training)
    * [ Memberships at Loftus ](/train/memberships-passes)
    * [ Fitness Facilities ](/train/fitness-facilities)
    * [ BEGIN Program ](/train/begin-program)
    * [ Personal Training ](/train/personal-training)
    * [ Group Exercise Classes ](/train/group-fitness-classes)
    * [ Timetables ](/train/timetables)
    * [ MyZone ](/train/myzone)
    * [ Seniors Exercise Program ](/train/sep)
    * [ Take Charge! Program ](/train/take-charge-program)
    * [ Member Benefits ](/train/member-benefits)
Close 

  * Sports

    * [ Social Sport Competitions ](/play/competitions)
    * [ Basketball ](/play/basketball)
    * [ Netball ](/play/netball)
    * [ Indoor and Outdoor Futsal ](/play/futsal)
    * [ Rebound Soccer ](/play/rebound-soccer)
    * [ Volleyball ](/play/volleyball)
    * [ Court Hire ](/play/court-hire)
    * [ Inclusive Activities ](/play/inclusive-activities)
Close 

  * Venue

    * [ News/Blog ](/venue/news-blog)
    * [ What's On ](/venue/whats-on)
    * [ Cafe ](/venue/cafe)
    * [ Telehealth ](/venue/tele-health)
    * [ Physiotherapy ](/venue/exercise-physiology)
    * [ Room Hire ](/venue/room-hire)
    * [ Timetables ](/venue/timetables)
    * [ FAQs ](/venue/faqs)
    * [ About Us ](/venue/about-us)
    * [ Your Membership App ](/venue/active-world)
Close 

  * Join

    * [ Member Benefits ](/join/member-benefits)
    * [ Memberships at Loftus ](/join/loftus-memberships)
    * [ Claim Your Free Trial ](/join/1-day-free-trial)
Close 

  * Contact Us

    * [ Customer Service Charter ](/contact-us/customer-service-charter)
    * [ Get in Touch ](/contact-us/get-in-touch)
    * [ Getting to Loftus Recreation Centre ](/contact-us/location)
    * [ Employment ](/contact-us/employment)
    * [ Manage My Membership ](/contact-us/manage-membership)
    * [ Membership Enquiry ](/contact-us/membership-enquiry)
Close 

  * Search 

Search

Search 




  * [ ](/)
  * Sports
  * Inclusive Activities 



# Inclusive Activities

## 

### Inclusive Activities at Loftus

Loftus Recreation centre is an inclusive facility in which everyone is welcome. Every person has the right to join into the gym, any Group Fitness Class or sporting activity.

### TripAdvisor Panel

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut quis fermentum dolor, in mollis lacus. Morbi pulvinar sem tortor, aliquet suscipit erat sollicitudin sed. Nulla ultricies convallis ipsum, ac semper sapien sollicitudin non. Vestibulum lobortis turpis purus, sed rutrum dolor mattis in. Aenean dapibus pellentesque nisi in convallis. Nulla a sapien tincidunt, convallis nunc vitae, iaculis lectus. Integer pellentesque venenatis pellentesque. Quisque vel pellentesque diam. In accumsan accumsan risus et porta. Aliquam a quam ut enim facilisis gravida. Aenean finibus metus justo, scelerisque euismod metus semper vitae. Phasellus non risus libero.

  * [About Us](/footer-links/about-us)
  * [Customer Service Charter](/footer-links/customer-service-charter)
  * [Inclusive Activities](/footer-links/inclusive-activities)
  * [FAQs](/footer-links/faqs)
  * [Employment](/footer-links/employment)
  * [Memberships](/footer-links/memberships)
  * [Blog/News](/footer-links/blog-news)
  * [Events](/footer-links/events)
  * [Privacy Policy](/footer-links/privacy-policy)



###  Contact us 

  * 99 Loftus Street, Leederville - 6007 
  * 08 9227 6526 


  * [ ](https://www.instagram.com/loftusrec)
  * [ ](https://www.facebook.com/LoftusRec)
  * [ ](https://www.youtube.com/channel/UC4MKxP96QCfcxfyBWCsc33A)



[ ](https://www.belgraviafoundation.org.au/our-purpose) [ ](http://www.companioncard.org.au/)

[Proudly managed by Belgravia Leisure](https://belgravialeisure.com.au)


---

## Page 4: https://www.loftusrecreationcentre.com.au/join/loftus-memberships

[](/)

[ 08 9227 6526 ](tel:08 9227 6526)

[ Membership ](https://www.loftusrecreationcentre.com.au:443/join/loftus-memberships) [ Free Trial ](https://www.loftusrecreationcentre.com.au:443/join/1-day-free-trial)

  * Junior

    * [ School Holiday Program ](/junior/school-holiday-activities)
Close 

  * Train

    * [ Reformer Pilates ](/train/reformer-pilates-\(1\))
    * [ B Active Functional Training ](/train/b-active-functional-training)
    * [ Memberships at Loftus ](/train/memberships-passes)
    * [ Fitness Facilities ](/train/fitness-facilities)
    * [ BEGIN Program ](/train/begin-program)
    * [ Personal Training ](/train/personal-training)
    * [ Group Exercise Classes ](/train/group-fitness-classes)
    * [ Timetables ](/train/timetables)
    * [ MyZone ](/train/myzone)
    * [ Seniors Exercise Program ](/train/sep)
    * [ Take Charge! Program ](/train/take-charge-program)
    * [ Member Benefits ](/train/member-benefits)
Close 

  * Sports

    * [ Social Sport Competitions ](/play/competitions)
    * [ Basketball ](/play/basketball)
    * [ Netball ](/play/netball)
    * [ Indoor and Outdoor Futsal ](/play/futsal)
    * [ Rebound Soccer ](/play/rebound-soccer)
    * [ Volleyball ](/play/volleyball)
    * [ Court Hire ](/play/court-hire)
    * [ Inclusive Activities ](/play/inclusive-activities)
Close 

  * Venue

    * [ News/Blog ](/venue/news-blog)
    * [ What's On ](/venue/whats-on)
    * [ Cafe ](/venue/cafe)
    * [ Telehealth ](/venue/tele-health)
    * [ Physiotherapy ](/venue/exercise-physiology)
    * [ Room Hire ](/venue/room-hire)
    * [ Timetables ](/venue/timetables)
    * [ FAQs ](/venue/faqs)
    * [ About Us ](/venue/about-us)
    * [ Your Membership App ](/venue/active-world)
Close 

  * Join

    * [ Member Benefits ](/join/member-benefits)
    * [ Memberships at Loftus ](/join/loftus-memberships)
    * [ Claim Your Free Trial ](/join/1-day-free-trial)
Close 

  * Contact Us

    * [ Customer Service Charter ](/contact-us/customer-service-charter)
    * [ Get in Touch ](/contact-us/get-in-touch)
    * [ Getting to Loftus Recreation Centre ](/contact-us/location)
    * [ Employment ](/contact-us/employment)
    * [ Manage My Membership ](/contact-us/manage-membership)
    * [ Membership Enquiry ](/contact-us/membership-enquiry)
Close 

  * Search 

Search

Search 




  * [ ](/)
  * Join
  * Memberships 



# Memberships at Loftus

## 

# ***REFORMER PILATES IS NOW AT LOFTUS***

  
The gym at Loftus Recreation Centre is one of the best equipped in the area. As a new member, you will have access to our complimentary and personalised fitness program BEGIN, to assist you in achieving your fitness goals faster. The Begin program is a staged process of consultation, goal-setting and instruction on how to use the equipment, that will leave you with a personalised program and the confidence to achieve your goals. You can find out more [here](https://www.loftusrecreationcentre.com.au/train/begin-program)

### _"In the last 8 months I have lost 12kg and gained strength and muscle mass. Having the Begin program to check in regularly and make sure I am on track has been a great help. Combining the program written for me with Spin classes has allowed me to achieve success so far"_

### _\- Olivia_

Our staff are all fully qualified health professionals and will take personal care to ensure that along with your gym membership, you also achieve the health and fitness results you're after.

  * 24/7 Gym Access (with 24/7 pass)
  * Group Fitness
  * No Locked-In Contract
  * Free Casual Sport Court Use



### Not enough for you? Why not check out our Premier Membership with all of the inclusions above, plus Reformer Pilates and Functional Training

[Premier Membership](https://www.loftusrecreationcentre.com.au/train/b-active-functional-training)

## TeenFit Gym Membership

For 13-15 year olds, just $16.40 per week. Membership includes access to the Health Club plus Free Casual Sport Court Use.  
  
Please visit us in centre with your parents/carers to join or call 9227 6526 with any questions. Thank you.  


[JOIN NOW](https://blau.activeworld.com.au/register?centre_name=Loftus%20Recreation%20Centre&for_what=membership&mpc_code=LRC-FA-FA-DD)

[View Group Fitness Timetable](/train/timetables)

### Standard Flexi Membership

For only $20.50 per week, will give you the flexibility to take control of achieving your health and fitness goals! Don't be stuck with a lock-in contract. Get access to a state of the art gym and a multitude of group exercise classes.

[ Join Today ](https://blau.activeworld.com.au/purchase_membership?centre_name=Loftus Recreation Centre&for_what=membership&mpc_code=LRC-FA-FA-DD)

### Student Flexi Membership

For only $19 per week, we can give you the flexibility to take control to achieve your health and fitness goals! Don't want to be stuck with a lock-in contract. Unlimited group exercise classes and 24/7 gym access.

[ Join Today ](https://blau.activeworld.com.au/purchase_membership?centre_name=Loftus Recreation Centre&for_what=membership&mpc_code=LRC-FA-FA-DD)

### Seniors Flexi Membership

For only $16.40 per week, you will receive 3 initial Personal Trainer appointments which will provide you the support and guidance you need. Unlimited Access to our results based Seniors Program, health club and group exercise classes.

[ Join Today ](https://blau.activeworld.com.au/purchase_membership?centre_name=Loftus Recreation Centre&for_what=membership&mpc_code=LRC-FA-FA-DD)

##  Common Membership Questions Expand all 

#####  Can I buy multiple Group Exercise Passes? 

Yes we have many packs to choose from at affordable prices.

#### Group Exercise Visit Passes:

10 Pack = $180.00  
20 Pack = $340.00

#### Full Access Visit Passes:

10 Pack = $195.00  
20 Pack = $360.00  
  
[Learn More](/train/group-fitness-classes)

#####  Why should I join? 

Because we guarantee results! Our memberships include 3 free fitness sessions with a qualified Fitness Coach where you will be provided a personalised program, expert instruction, ongoing benchmarks to track your progress and information to help you get on track with the right eating habits.

#####  What are the fees? 

We will be able to assist you in finding the most cost-effective membership to suit you. With various membership options that cater for all members of the community, our Member Care Consultant will be in touch to get you started on your goals with the right option.

#####  Can I try before I buy? 

Yes you can! Simply click the button below and fill out the form to enjoy access to our health club. When you’re ready to continue with ongoing access, we’ll help you find the best option to get started.

[Free Trial](/join/1-day-free-trial)

#####  Do you provide health assessments? 

When you become a member, you will receive 3 free fitness sessions through our exclusive Begin Program. As an added bonus, you will receive free ongoing assessments or new program every eight weeks with a qualified Fitness Coach.

#####  Can I use my concession card? 

Just let one of our friendly Customer Care Consultants know as you may be eligible for a discount!

### TripAdvisor Panel

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut quis fermentum dolor, in mollis lacus. Morbi pulvinar sem tortor, aliquet suscipit erat sollicitudin sed. Nulla ultricies convallis ipsum, ac semper sapien sollicitudin non. Vestibulum lobortis turpis purus, sed rutrum dolor mattis in. Aenean dapibus pellentesque nisi in convallis. Nulla a sapien tincidunt, convallis nunc vitae, iaculis lectus. Integer pellentesque venenatis pellentesque. Quisque vel pellentesque diam. In accumsan accumsan risus et porta. Aliquam a quam ut enim facilisis gravida. Aenean finibus metus justo, scelerisque euismod metus semper vitae. Phasellus non risus libero.

  * [About Us](/footer-links/about-us)
  * [Customer Service Charter](/footer-links/customer-service-charter)
  * [Inclusive Activities](/footer-links/inclusive-activities)
  * [FAQs](/footer-links/faqs)
  * [Employment](/footer-links/employment)
  * [Memberships](/footer-links/memberships)
  * [Blog/News](/footer-links/blog-news)
  * [Events](/footer-links/events)
  * [Privacy Policy](/footer-links/privacy-policy)



###  Contact us 

  * 99 Loftus Street, Leederville - 6007 
  * 08 9227 6526 


  * [ ](https://www.instagram.com/loftusrec)
  * [ ](https://www.facebook.com/LoftusRec)
  * [ ](https://www.youtube.com/channel/UC4MKxP96QCfcxfyBWCsc33A)



[ ](https://www.belgraviafoundation.org.au/our-purpose) [ ](http://www.companioncard.org.au/)

[Proudly managed by Belgravia Leisure](https://belgravialeisure.com.au)


---

## Page 5: https://www.loftusrecreationcentre.com.au/train/reformer-pilates-(1)

[](/)

[ 08 9227 6526 ](tel:08 9227 6526)

[ Membership ](https://www.loftusrecreationcentre.com.au:443/join/loftus-memberships) [ Free Trial ](https://www.loftusrecreationcentre.com.au:443/join/1-day-free-trial)

  * Junior

    * [ School Holiday Program ](/junior/school-holiday-activities)
Close 

  * Train

    * [ Reformer Pilates ](/train/reformer-pilates-\(1\))
    * [ B Active Functional Training ](/train/b-active-functional-training)
    * [ Memberships at Loftus ](/train/memberships-passes)
    * [ Fitness Facilities ](/train/fitness-facilities)
    * [ BEGIN Program ](/train/begin-program)
    * [ Personal Training ](/train/personal-training)
    * [ Group Exercise Classes ](/train/group-fitness-classes)
    * [ Timetables ](/train/timetables)
    * [ MyZone ](/train/myzone)
    * [ Seniors Exercise Program ](/train/sep)
    * [ Take Charge! Program ](/train/take-charge-program)
    * [ Member Benefits ](/train/member-benefits)
Close 

  * Sports

    * [ Social Sport Competitions ](/play/competitions)
    * [ Basketball ](/play/basketball)
    * [ Netball ](/play/netball)
    * [ Indoor and Outdoor Futsal ](/play/futsal)
    * [ Rebound Soccer ](/play/rebound-soccer)
    * [ Volleyball ](/play/volleyball)
    * [ Court Hire ](/play/court-hire)
    * [ Inclusive Activities ](/play/inclusive-activities)
Close 

  * Venue

    * [ News/Blog ](/venue/news-blog)
    * [ What's On ](/venue/whats-on)
    * [ Cafe ](/venue/cafe)
    * [ Telehealth ](/venue/tele-health)
    * [ Physiotherapy ](/venue/exercise-physiology)
    * [ Room Hire ](/venue/room-hire)
    * [ Timetables ](/venue/timetables)
    * [ FAQs ](/venue/faqs)
    * [ About Us ](/venue/about-us)
    * [ Your Membership App ](/venue/active-world)
Close 

  * Join

    * [ Member Benefits ](/join/member-benefits)
    * [ Memberships at Loftus ](/join/loftus-memberships)
    * [ Claim Your Free Trial ](/join/1-day-free-trial)
Close 

  * Contact Us

    * [ Customer Service Charter ](/contact-us/customer-service-charter)
    * [ Get in Touch ](/contact-us/get-in-touch)
    * [ Getting to Loftus Recreation Centre ](/contact-us/location)
    * [ Employment ](/contact-us/employment)
    * [ Manage My Membership ](/contact-us/manage-membership)
    * [ Membership Enquiry ](/contact-us/membership-enquiry)
Close 

  * Search 

Search

Search 




  * [ ](/)
  * Train
  * Reformer Pilates 



# Reformer Pilates

## Unlimited Reformer Pilates Classes $49.95 pw

  
We are excited to share with you that our Reformer Pilates studio is now open.**** Reformer Pilates classes are available on our new Premium Membership.

Your new Premium Membership will include:

  * Unlimited Reformer Pilates classes
  * Unlimited 24/7 gym access
  * Unlimited Group Excercise classes
  * Unlimited Group Functional Training classes
  * Ongoing trainer support with our [Begin Program](https://www.loftusrecreationcentre.com.au/train/begin-program)



Reformer Pilates is designed for all fitness and ability levels. Using spring loaded resistance on a reformer bed, our coaches will guide you through a variety of exercises designed to increase your strength, mobility, coordination and balance. To find out more, speak to our friendly team today!   


### Class Waitlist

At Loftus Recreation Centre, we strive to provide fair and accessible booking opportunities for all members. As our Reformer Pilates classes are quite busy, we have implemented a class waitlist. When a member is booking classes and encounters one that is at capacity, they will instead be invited to join the waitlist. If a member booked into the class then cancels their booking, the next member on the waitlist will be automatically added to the class and receive an email notification.  
To ensure smooth class operations and fairness for all of our members, we have implemented the following policy regarding class cancellations and no-shows.  


### **Online Class Booking Cancellation & No-Show Policy**

**1\. Cancellation Policy:**

  * Members must cancel their class booking at least 1 hour before the class start time to avoid penalties.
  * Cancellations can be made via the Active World App by the Notify Absence button in My Schedule, email to [loftusreception@belgravialeisure.com.au](mailto:loftusreception@belgravialeisure.com.au?subject=Class%20Booking%20Cancellation&body=Hi,%0a%0aMy%20name%20is%20\[first%20&%20last%20name\]%20and%20I%20would%20like%20to%20cancel%20my%20booking%20for%20the%20following%20Reformer%20Pilates%20class.%0aDate:%20%0aTime:) and/or calling the centre directly via 0439 205 320

**2\. No-Show Policy:**

  * Failure to attend a booked class without cancelling in advance will be considered a no-show. Repeated no-shows within the same calendar year will result in the following consequences:
  * First No-Show: A warning email will be sent as a reminder to cancel future booking(s) if unable to attend.
  * Second No-Show: The member’s ability to book classes will be suspended for one week, with future booked classes for the upcoming week removed, restricting attendance to classes during this period.

**3\. Reactivation After Suspension:**

  * After a one-week class booking suspension, booking access will be automatically reinstated.
  * Continued no-shows after reinstatement may result in further restrictions or lengthier booking suspensions, at the discretion of Centre Management.

  
We appreciate your cooperation in respecting this policy to ensure all members have equal access to our classes. If you have any questions or need assistance, please contact our team. 

## GET STARTED

[VIEW OUR TIMETABLE HERE](/getmedia/31b432d7-8ad9-434a-9ad0-192fae7488f0/loftus-reformer-timetable-5jul25.pdf)

[Join](https://blau.activeworld.com.au/register?centre_name=Loftus%20Recreation%20Centre&for_what=membership&mpc_code=LRC-FA-FA-DD) [Book your free trial](https://www.loftusrecreationcentre.com.au/join/1-day-free-trial)

### TripAdvisor Panel

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut quis fermentum dolor, in mollis lacus. Morbi pulvinar sem tortor, aliquet suscipit erat sollicitudin sed. Nulla ultricies convallis ipsum, ac semper sapien sollicitudin non. Vestibulum lobortis turpis purus, sed rutrum dolor mattis in. Aenean dapibus pellentesque nisi in convallis. Nulla a sapien tincidunt, convallis nunc vitae, iaculis lectus. Integer pellentesque venenatis pellentesque. Quisque vel pellentesque diam. In accumsan accumsan risus et porta. Aliquam a quam ut enim facilisis gravida. Aenean finibus metus justo, scelerisque euismod metus semper vitae. Phasellus non risus libero.

  * [About Us](/footer-links/about-us)
  * [Customer Service Charter](/footer-links/customer-service-charter)
  * [Inclusive Activities](/footer-links/inclusive-activities)
  * [FAQs](/footer-links/faqs)
  * [Employment](/footer-links/employment)
  * [Memberships](/footer-links/memberships)
  * [Blog/News](/footer-links/blog-news)
  * [Events](/footer-links/events)
  * [Privacy Policy](/footer-links/privacy-policy)



###  Contact us 

  * 99 Loftus Street, Leederville - 6007 
  * 08 9227 6526 


  * [ ](https://www.instagram.com/loftusrec)
  * [ ](https://www.facebook.com/LoftusRec)
  * [ ](https://www.youtube.com/channel/UC4MKxP96QCfcxfyBWCsc33A)



[ ](https://www.belgraviafoundation.org.au/our-purpose) [ ](http://www.companioncard.org.au/)

[Proudly managed by Belgravia Leisure](https://belgravialeisure.com.au)


---

## Page 6: https://www.loftusrecreationcentre.com.au/junior/school-holiday-activities

[](/)

[ 08 9227 6526 ](tel:08 9227 6526)

[ Membership ](https://www.loftusrecreationcentre.com.au:443/join/loftus-memberships) [ Free Trial ](https://www.loftusrecreationcentre.com.au:443/join/1-day-free-trial)

  * Junior

    * [ School Holiday Program ](/junior/school-holiday-activities)
Close 

  * Train

    * [ Reformer Pilates ](/train/reformer-pilates-\(1\))
    * [ B Active Functional Training ](/train/b-active-functional-training)
    * [ Memberships at Loftus ](/train/memberships-passes)
    * [ Fitness Facilities ](/train/fitness-facilities)
    * [ BEGIN Program ](/train/begin-program)
    * [ Personal Training ](/train/personal-training)
    * [ Group Exercise Classes ](/train/group-fitness-classes)
    * [ Timetables ](/train/timetables)
    * [ MyZone ](/train/myzone)
    * [ Seniors Exercise Program ](/train/sep)
    * [ Take Charge! Program ](/train/take-charge-program)
    * [ Member Benefits ](/train/member-benefits)
Close 

  * Sports

    * [ Social Sport Competitions ](/play/competitions)
    * [ Basketball ](/play/basketball)
    * [ Netball ](/play/netball)
    * [ Indoor and Outdoor Futsal ](/play/futsal)
    * [ Rebound Soccer ](/play/rebound-soccer)
    * [ Volleyball ](/play/volleyball)
    * [ Court Hire ](/play/court-hire)
    * [ Inclusive Activities ](/play/inclusive-activities)
Close 

  * Venue

    * [ News/Blog ](/venue/news-blog)
    * [ What's On ](/venue/whats-on)
    * [ Cafe ](/venue/cafe)
    * [ Telehealth ](/venue/tele-health)
    * [ Physiotherapy ](/venue/exercise-physiology)
    * [ Room Hire ](/venue/room-hire)
    * [ Timetables ](/venue/timetables)
    * [ FAQs ](/venue/faqs)
    * [ About Us ](/venue/about-us)
    * [ Your Membership App ](/venue/active-world)
Close 

  * Join

    * [ Member Benefits ](/join/member-benefits)
    * [ Memberships at Loftus ](/join/loftus-memberships)
    * [ Claim Your Free Trial ](/join/1-day-free-trial)
Close 

  * Contact Us

    * [ Customer Service Charter ](/contact-us/customer-service-charter)
    * [ Get in Touch ](/contact-us/get-in-touch)
    * [ Getting to Loftus Recreation Centre ](/contact-us/location)
    * [ Employment ](/contact-us/employment)
    * [ Manage My Membership ](/contact-us/manage-membership)
    * [ Membership Enquiry ](/contact-us/membership-enquiry)
Close 

  * Search 

Search

Search 




  * [ ](/)
  * Junior
  * School Holiday Program 



# 

## 

Loftus Recreation Centre is excited to offer a sports-based School Holiday program for children aged between 5 and 12!  
  
Your child will have a blast playing a variety of sports including Basketball, Soccer, Netball, AFL, Touch Rugby, Golf, Kickball, and more.  
  
Sessions available across every School Holiday break from 9am - 3pm daily.  
  
Children can bring their own morning tea and lunch, or a lunch order can be placed, on arrival at the sign in desk, from our kiosk.

**_Program Structure_**

**Morning Session (9:00 AM - 12:30 PM):**

  * Sports include basketball, soccer, netball, golf, touch rugby, cricket, AFL, and kickball.

  * Themed games and activities focusing on skill building.

  * Coaches verse kid’s games.

  * Activities tailored to suit the age and skill level of children.




**Morning Tea (10:30) & Lunch (12:30):**

  * Supervised break for kids to eat and socialise.

  * Children can bring their own morning tea and lunch, or a lunch order can be placed, on arrival at the sign in desk, from our kiosk.

  * Children _must bring their own_ water bottles.

  * Please be mindful of possible allergies when packing your child's lunch. This program is a nut free zone.




**Afternoon Session (12:30 PM - 3:00 PM):**

  * Continuation of morning session sports

  * Coaches verse kid’s games

  * Multi-sports activities. E.g., Circuits, Sports ‘Olympics’, Games, Yoga, etc.




**_What to Pack_**

  * Morning tea & lunch (nut free zone), if not placing a lunch order.

  * Water bottle.

  * Sun safe hat and sunscreen.

  * Your own ball for the chosen sport (not compulsory) - please remember this is your responsibility and Loftus takes no responsibility for any lost items.

  * Closed in shoes and sports appropriate clothing for court games. 




**_Your child will not be able to partake in activities safely if they are not wearing enclosed, sports appropriate shoes/clothing, and may miss out)._**

##   
School Holiday Dates 2026/27

**TERM 1**  
(Autumn)  | **TERM 2**  
(Winter) | **TERM 3**  
(Spring)  | **TERM 4**  
(Summer)  
---|---|---|---  
April 3rd to April 19th  | July 4th to July 19th | Sept 26th to Oct 11th  | Dec 18th to Jan 31st  
  
### 

### 

_**[TO REGISTER  
PLEASE CLICK HERE](https://www.trybooking.com/events/landing/1503139)**_

  
If you have any questions, please email the team at _loftusprograms@belgravialeisure.com.au_

### Summer Holiday 2026 Dates

**WEEK 1** : 5th of Jan - 9th of Jan  
**WEEK 2** : 12th of Jan - 16th of Jan  
**WEEK 3** : 19th of Jan - 23rd of Jan  
**WEEK 4** : 26th of Jan - 30th of Jan

## 

### REGISTRATION

At Loftus Recreation Centre, we ensure that learning and development are undertaken in a safe and nurturing environment across all programs. We focus on providing a fun and inclusive outlook on fitness and sports ensuring all children are having fun!

[ CLICK TO BOOK ](https://www.trybooking.com/events/landing/1503139)

## 

[ ](/getmedia/78d9c5df-db79-4490-af19-94ce6c9a5762/sha-gallery-01.png?ext=.png) [ ](/getmedia/742c0e02-e16f-499b-b297-c2292931529d/sha-gallery-02.png?ext=.png) [ ](/getmedia/281630cb-450a-48b6-a68a-456ed6962203/sha-gallery-03.png?ext=.png) [ ](/getmedia/7ed17a00-ae9f-4df4-9baf-a99de9c68709/sha-gallery-04.png?ext=.png) [ ](/getmedia/0c029503-8894-4dde-9dc6-7304c1ab40fb/sha-gallery-05.png?ext=.png) [ ](/getmedia/c60697da-1f33-4d33-b105-ad09a2a9addf/sha-gallery-06.png?ext=.png) [ ](/getmedia/1b1d5b0b-2137-45b4-949b-fc5f6f18cf99/sha-gallery-07.png?ext=.png) [ ](/getmedia/763fab7f-e995-4396-8760-90ed8301197b/sha-gallery-08.png?ext=.png)

### TripAdvisor Panel

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut quis fermentum dolor, in mollis lacus. Morbi pulvinar sem tortor, aliquet suscipit erat sollicitudin sed. Nulla ultricies convallis ipsum, ac semper sapien sollicitudin non. Vestibulum lobortis turpis purus, sed rutrum dolor mattis in. Aenean dapibus pellentesque nisi in convallis. Nulla a sapien tincidunt, convallis nunc vitae, iaculis lectus. Integer pellentesque venenatis pellentesque. Quisque vel pellentesque diam. In accumsan accumsan risus et porta. Aliquam a quam ut enim facilisis gravida. Aenean finibus metus justo, scelerisque euismod metus semper vitae. Phasellus non risus libero.

  * [About Us](/footer-links/about-us)
  * [Customer Service Charter](/footer-links/customer-service-charter)
  * [Inclusive Activities](/footer-links/inclusive-activities)
  * [FAQs](/footer-links/faqs)
  * [Employment](/footer-links/employment)
  * [Memberships](/footer-links/memberships)
  * [Blog/News](/footer-links/blog-news)
  * [Events](/footer-links/events)
  * [Privacy Policy](/footer-links/privacy-policy)



###  Contact us 

  * 99 Loftus Street, Leederville - 6007 
  * 08 9227 6526 


  * [ ](https://www.instagram.com/loftusrec)
  * [ ](https://www.facebook.com/LoftusRec)
  * [ ](https://www.youtube.com/channel/UC4MKxP96QCfcxfyBWCsc33A)



[ ](https://www.belgraviafoundation.org.au/our-purpose) [ ](http://www.companioncard.org.au/)

[Proudly managed by Belgravia Leisure](https://belgravialeisure.com.au)


---

## Page 7: https://www.loftusrecreationcentre.com.au/train/begin-program

[](/)

[ 08 9227 6526 ](tel:08 9227 6526)

[ Membership ](https://www.loftusrecreationcentre.com.au:443/join/loftus-memberships) [ Free Trial ](https://www.loftusrecreationcentre.com.au:443/join/1-day-free-trial)

  * Junior

    * [ School Holiday Program ](/junior/school-holiday-activities)
Close 

  * Train

    * [ Reformer Pilates ](/train/reformer-pilates-\(1\))
    * [ B Active Functional Training ](/train/b-active-functional-training)
    * [ Memberships at Loftus ](/train/memberships-passes)
    * [ Fitness Facilities ](/train/fitness-facilities)
    * [ BEGIN Program ](/train/begin-program)
    * [ Personal Training ](/train/personal-training)
    * [ Group Exercise Classes ](/train/group-fitness-classes)
    * [ Timetables ](/train/timetables)
    * [ MyZone ](/train/myzone)
    * [ Seniors Exercise Program ](/train/sep)
    * [ Take Charge! Program ](/train/take-charge-program)
    * [ Member Benefits ](/train/member-benefits)
Close 

  * Sports

    * [ Social Sport Competitions ](/play/competitions)
    * [ Basketball ](/play/basketball)
    * [ Netball ](/play/netball)
    * [ Indoor and Outdoor Futsal ](/play/futsal)
    * [ Rebound Soccer ](/play/rebound-soccer)
    * [ Volleyball ](/play/volleyball)
    * [ Court Hire ](/play/court-hire)
    * [ Inclusive Activities ](/play/inclusive-activities)
Close 

  * Venue

    * [ News/Blog ](/venue/news-blog)
    * [ What's On ](/venue/whats-on)
    * [ Cafe ](/venue/cafe)
    * [ Telehealth ](/venue/tele-health)
    * [ Physiotherapy ](/venue/exercise-physiology)
    * [ Room Hire ](/venue/room-hire)
    * [ Timetables ](/venue/timetables)
    * [ FAQs ](/venue/faqs)
    * [ About Us ](/venue/about-us)
    * [ Your Membership App ](/venue/active-world)
Close 

  * Join

    * [ Member Benefits ](/join/member-benefits)
    * [ Memberships at Loftus ](/join/loftus-memberships)
    * [ Claim Your Free Trial ](/join/1-day-free-trial)
Close 

  * Contact Us

    * [ Customer Service Charter ](/contact-us/customer-service-charter)
    * [ Get in Touch ](/contact-us/get-in-touch)
    * [ Getting to Loftus Recreation Centre ](/contact-us/location)
    * [ Employment ](/contact-us/employment)
    * [ Manage My Membership ](/contact-us/manage-membership)
    * [ Membership Enquiry ](/contact-us/membership-enquiry)
Close 

  * Search 

Search

Search 




  * [ ](/)
  * Train
  * BEGIN Program 



# BEGIN Program

## 

## Our BEGIN Program

Our qualified and experienced fitness professionals will provide you with tailored guidance and support, to ensure you are equipped with the knowledge and know how to help you achieve your health and wellbeing goals. 

Benefits of BEGIN:

  * Completely FREE for full access members 
  * Ongoing support to reach your fitness goals 
  * Guidance tailored to your fitness experience and lifestyle 
  * Maximise your results to look and feel your best 



## How To BEGIN

Become a full access member to receive the best start to your fitness journey with our BEGIN program. Click below to get started now or enquire about the program and book in your 3 FREE appointments. 

[BECOME A MEMBER](/join/memberships) [ENQUIRE ABOUT BEGIN](/contact-us/get-in-touch)

## 

### Your First 30 Days

Three complimentary appointments

**Appointment 1 - Beginning** _(Day 1- 3 of membership)_  
From the Beginning we will take the time to understand your goals, your motivations and your reasons to change. We will build a baseline to measure and map your progress and develop a personalised gym program designed and demonstrated to you.   
  
**Appointment 2 - Check-In** _(Day 14 -17 of membership)_  
Your Check-In is the appointment which will take place approximately two weeks after your Beginning appointment. Here, we will focus on how you are finding your personalised program and where we can make any changes to ensure you’re on the right track.   
  
**Appointment 3 - Benefits** _(Day 30 of membership)_  
In your third appointment, we will re-visit your Beginning baseline markers and review how we have progressed in the initial 30 days and the Benefits you have gained. Your trainer can change up your program at this time and provide guidance on your next steps with assisted or accelerated training programs.

### 

[ ](/getmedia/c95ae9e8-8109-4f0d-8b72-c4fa639a0d08/BEGIN-website-testimonials-1.png?ext=.png) [ ](/getmedia/b9f93ee2-1078-4af2-bfb3-7df8628e0281/BEGIN-website-testimonials2.png?ext=.png) [ ](/getmedia/3c5d08e7-f5c1-4c2c-b105-3d81c38cdb9a/BEGIN-website-testimonials3.png?ext=.png) [ ](/getmedia/47c4a9d3-ff9e-44f9-97d4-653396f73cff/BEGIN-website-testimonials4.png?ext=.png) [ ](/getmedia/0e2d4ef5-e83f-47ac-8e0e-2b768abdf389/BEGIN-website-testimonials5.png?ext=.png)

##  BEGIN FAQs Expand all 

#####  Can I access BEGIN if I am already a member? 

Absolutely! Talk to reception or a trainer when you are in centre next to book in your appointment!

#####  How do I access the BEGIN program? 

BEGIN is available to all full access members of our facility.   
If you are already a member, talk to our team or reception to book your consultation with a trainer.  
  
Not a member? Get started today!

#####  What are the benefits of BEGIN? 

  * A free program for all full access members. 
  * Build upon and strengthen your mental, emotional and physical attributes.
  * Receive a tailored exercise program using the latest in scientific methods.
  * Ongoing support to keep members looking and feeling their best.



#####  What can I expect from BEGIN? 

All new members receive three (3) sessions in your first four weeks of joining our club. You'll meet with one of our highly qualified health professionals who will take you through the Begin program.   
  
Determining your current health and fitness ability and recommend a custom exercise program tailored to your individual needs.  
  
To ensure you don't get bored of your specialised fitness program we apply time efficient and effective techniques.  
  
Tailoring each member’s personal fitness plan by using the latest in scientific approaches, ensuring we create the perfect program for you!

### TripAdvisor Panel

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut quis fermentum dolor, in mollis lacus. Morbi pulvinar sem tortor, aliquet suscipit erat sollicitudin sed. Nulla ultricies convallis ipsum, ac semper sapien sollicitudin non. Vestibulum lobortis turpis purus, sed rutrum dolor mattis in. Aenean dapibus pellentesque nisi in convallis. Nulla a sapien tincidunt, convallis nunc vitae, iaculis lectus. Integer pellentesque venenatis pellentesque. Quisque vel pellentesque diam. In accumsan accumsan risus et porta. Aliquam a quam ut enim facilisis gravida. Aenean finibus metus justo, scelerisque euismod metus semper vitae. Phasellus non risus libero.

  * [About Us](/footer-links/about-us)
  * [Customer Service Charter](/footer-links/customer-service-charter)
  * [Inclusive Activities](/footer-links/inclusive-activities)
  * [FAQs](/footer-links/faqs)
  * [Employment](/footer-links/employment)
  * [Memberships](/footer-links/memberships)
  * [Blog/News](/footer-links/blog-news)
  * [Events](/footer-links/events)
  * [Privacy Policy](/footer-links/privacy-policy)



###  Contact us 

  * 99 Loftus Street, Leederville - 6007 
  * 08 9227 6526 


  * [ ](https://www.instagram.com/loftusrec)
  * [ ](https://www.facebook.com/LoftusRec)
  * [ ](https://www.youtube.com/channel/UC4MKxP96QCfcxfyBWCsc33A)



[ ](https://www.belgraviafoundation.org.au/our-purpose) [ ](http://www.companioncard.org.au/)

[Proudly managed by Belgravia Leisure](https://belgravialeisure.com.au)


---

## Page 8: https://www.loftusrecreationcentre.com.au/train/memberships-passes

[](/)

[ 08 9227 6526 ](tel:08 9227 6526)

[ Membership ](https://www.loftusrecreationcentre.com.au:443/join/loftus-memberships) [ Free Trial ](https://www.loftusrecreationcentre.com.au:443/join/1-day-free-trial)

  * Junior

    * [ School Holiday Program ](/junior/school-holiday-activities)
Close 

  * Train

    * [ Reformer Pilates ](/train/reformer-pilates-\(1\))
    * [ B Active Functional Training ](/train/b-active-functional-training)
    * [ Memberships at Loftus ](/train/memberships-passes)
    * [ Fitness Facilities ](/train/fitness-facilities)
    * [ BEGIN Program ](/train/begin-program)
    * [ Personal Training ](/train/personal-training)
    * [ Group Exercise Classes ](/train/group-fitness-classes)
    * [ Timetables ](/train/timetables)
    * [ MyZone ](/train/myzone)
    * [ Seniors Exercise Program ](/train/sep)
    * [ Take Charge! Program ](/train/take-charge-program)
    * [ Member Benefits ](/train/member-benefits)
Close 

  * Sports

    * [ Social Sport Competitions ](/play/competitions)
    * [ Basketball ](/play/basketball)
    * [ Netball ](/play/netball)
    * [ Indoor and Outdoor Futsal ](/play/futsal)
    * [ Rebound Soccer ](/play/rebound-soccer)
    * [ Volleyball ](/play/volleyball)
    * [ Court Hire ](/play/court-hire)
    * [ Inclusive Activities ](/play/inclusive-activities)
Close 

  * Venue

    * [ News/Blog ](/venue/news-blog)
    * [ What's On ](/venue/whats-on)
    * [ Cafe ](/venue/cafe)
    * [ Telehealth ](/venue/tele-health)
    * [ Physiotherapy ](/venue/exercise-physiology)
    * [ Room Hire ](/venue/room-hire)
    * [ Timetables ](/venue/timetables)
    * [ FAQs ](/venue/faqs)
    * [ About Us ](/venue/about-us)
    * [ Your Membership App ](/venue/active-world)
Close 

  * Join

    * [ Member Benefits ](/join/member-benefits)
    * [ Memberships at Loftus ](/join/loftus-memberships)
    * [ Claim Your Free Trial ](/join/1-day-free-trial)
Close 

  * Contact Us

    * [ Customer Service Charter ](/contact-us/customer-service-charter)
    * [ Get in Touch ](/contact-us/get-in-touch)
    * [ Getting to Loftus Recreation Centre ](/contact-us/location)
    * [ Employment ](/contact-us/employment)
    * [ Manage My Membership ](/contact-us/manage-membership)
    * [ Membership Enquiry ](/contact-us/membership-enquiry)
Close 

  * Search 

Search

Search 




  * [ ](/)
  * Join
  * Memberships 



# Memberships at Loftus

## 

# ***REFORMER PILATES IS NOW AT LOFTUS***

  
The gym at Loftus Recreation Centre is one of the best equipped in the area. As a new member, you will have access to our complimentary and personalised fitness program BEGIN, to assist you in achieving your fitness goals faster. The Begin program is a staged process of consultation, goal-setting and instruction on how to use the equipment, that will leave you with a personalised program and the confidence to achieve your goals. You can find out more [here](https://www.loftusrecreationcentre.com.au/train/begin-program)

### _"In the last 8 months I have lost 12kg and gained strength and muscle mass. Having the Begin program to check in regularly and make sure I am on track has been a great help. Combining the program written for me with Spin classes has allowed me to achieve success so far"_

### _\- Olivia_

Our staff are all fully qualified health professionals and will take personal care to ensure that along with your gym membership, you also achieve the health and fitness results you're after.

  * 24/7 Gym Access (with 24/7 pass)
  * Group Fitness
  * No Locked-In Contract
  * Free Casual Sport Court Use



### Not enough for you? Why not check out our Premier Membership with all of the inclusions above, plus Reformer Pilates and Functional Training

[Premier Membership](https://www.loftusrecreationcentre.com.au/train/b-active-functional-training)

## TeenFit Gym Membership

For 13-15 year olds, just $16.40 per week. Membership includes access to the Health Club plus Free Casual Sport Court Use.  
  
Please visit us in centre with your parents/carers to join or call 9227 6526 with any questions. Thank you.  


[JOIN NOW](https://blau.activeworld.com.au/register?centre_name=Loftus%20Recreation%20Centre&for_what=membership&mpc_code=LRC-FA-FA-DD)

[View Group Fitness Timetable](/train/timetables)

### Standard Flexi Membership

For only $20.50 per week, will give you the flexibility to take control of achieving your health and fitness goals! Don't be stuck with a lock-in contract. Get access to a state of the art gym and a multitude of group exercise classes.

[ Join Today ](https://blau.activeworld.com.au/purchase_membership?centre_name=Loftus Recreation Centre&for_what=membership&mpc_code=LRC-FA-FA-DD)

### Student Flexi Membership

For only $19 per week, we can give you the flexibility to take control to achieve your health and fitness goals! Don't want to be stuck with a lock-in contract. Unlimited group exercise classes and 24/7 gym access.

[ Join Today ](https://blau.activeworld.com.au/purchase_membership?centre_name=Loftus Recreation Centre&for_what=membership&mpc_code=LRC-FA-FA-DD)

### Seniors Flexi Membership

For only $16.40 per week, you will receive 3 initial Personal Trainer appointments which will provide you the support and guidance you need. Unlimited Access to our results based Seniors Program, health club and group exercise classes.

[ Join Today ](https://blau.activeworld.com.au/purchase_membership?centre_name=Loftus Recreation Centre&for_what=membership&mpc_code=LRC-FA-FA-DD)

##  Common Membership Questions Expand all 

#####  Can I buy multiple Group Exercise Passes? 

Yes we have many packs to choose from at affordable prices.

#### Group Exercise Visit Passes:

10 Pack = $180.00  
20 Pack = $340.00

#### Full Access Visit Passes:

10 Pack = $195.00  
20 Pack = $360.00  
  
[Learn More](/train/group-fitness-classes)

#####  Why should I join? 

Because we guarantee results! Our memberships include 3 free fitness sessions with a qualified Fitness Coach where you will be provided a personalised program, expert instruction, ongoing benchmarks to track your progress and information to help you get on track with the right eating habits.

#####  What are the fees? 

We will be able to assist you in finding the most cost-effective membership to suit you. With various membership options that cater for all members of the community, our Member Care Consultant will be in touch to get you started on your goals with the right option.

#####  Can I try before I buy? 

Yes you can! Simply click the button below and fill out the form to enjoy access to our health club. When you’re ready to continue with ongoing access, we’ll help you find the best option to get started.

[Free Trial](/join/1-day-free-trial)

#####  Do you provide health assessments? 

When you become a member, you will receive 3 free fitness sessions through our exclusive Begin Program. As an added bonus, you will receive free ongoing assessments or new program every eight weeks with a qualified Fitness Coach.

#####  Can I use my concession card? 

Just let one of our friendly Customer Care Consultants know as you may be eligible for a discount!

### TripAdvisor Panel

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut quis fermentum dolor, in mollis lacus. Morbi pulvinar sem tortor, aliquet suscipit erat sollicitudin sed. Nulla ultricies convallis ipsum, ac semper sapien sollicitudin non. Vestibulum lobortis turpis purus, sed rutrum dolor mattis in. Aenean dapibus pellentesque nisi in convallis. Nulla a sapien tincidunt, convallis nunc vitae, iaculis lectus. Integer pellentesque venenatis pellentesque. Quisque vel pellentesque diam. In accumsan accumsan risus et porta. Aliquam a quam ut enim facilisis gravida. Aenean finibus metus justo, scelerisque euismod metus semper vitae. Phasellus non risus libero.

  * [About Us](/footer-links/about-us)
  * [Customer Service Charter](/footer-links/customer-service-charter)
  * [Inclusive Activities](/footer-links/inclusive-activities)
  * [FAQs](/footer-links/faqs)
  * [Employment](/footer-links/employment)
  * [Memberships](/footer-links/memberships)
  * [Blog/News](/footer-links/blog-news)
  * [Events](/footer-links/events)
  * [Privacy Policy](/footer-links/privacy-policy)



###  Contact us 

  * 99 Loftus Street, Leederville - 6007 
  * 08 9227 6526 


  * [ ](https://www.instagram.com/loftusrec)
  * [ ](https://www.facebook.com/LoftusRec)
  * [ ](https://www.youtube.com/channel/UC4MKxP96QCfcxfyBWCsc33A)



[ ](https://www.belgraviafoundation.org.au/our-purpose) [ ](http://www.companioncard.org.au/)

[Proudly managed by Belgravia Leisure](https://belgravialeisure.com.au)


---

## Page 9: https://www.loftusrecreationcentre.com.au/play/inclusive-activities

[](/)

[ 08 9227 6526 ](tel:08 9227 6526)

[ Membership ](https://www.loftusrecreationcentre.com.au:443/join/loftus-memberships) [ Free Trial ](https://www.loftusrecreationcentre.com.au:443/join/1-day-free-trial)

  * Junior

    * [ School Holiday Program ](/junior/school-holiday-activities)
Close 

  * Train

    * [ Reformer Pilates ](/train/reformer-pilates-\(1\))
    * [ B Active Functional Training ](/train/b-active-functional-training)
    * [ Memberships at Loftus ](/train/memberships-passes)
    * [ Fitness Facilities ](/train/fitness-facilities)
    * [ BEGIN Program ](/train/begin-program)
    * [ Personal Training ](/train/personal-training)
    * [ Group Exercise Classes ](/train/group-fitness-classes)
    * [ Timetables ](/train/timetables)
    * [ MyZone ](/train/myzone)
    * [ Seniors Exercise Program ](/train/sep)
    * [ Take Charge! Program ](/train/take-charge-program)
    * [ Member Benefits ](/train/member-benefits)
Close 

  * Sports

    * [ Social Sport Competitions ](/play/competitions)
    * [ Basketball ](/play/basketball)
    * [ Netball ](/play/netball)
    * [ Indoor and Outdoor Futsal ](/play/futsal)
    * [ Rebound Soccer ](/play/rebound-soccer)
    * [ Volleyball ](/play/volleyball)
    * [ Court Hire ](/play/court-hire)
    * [ Inclusive Activities ](/play/inclusive-activities)
Close 

  * Venue

    * [ News/Blog ](/venue/news-blog)
    * [ What's On ](/venue/whats-on)
    * [ Cafe ](/venue/cafe)
    * [ Telehealth ](/venue/tele-health)
    * [ Physiotherapy ](/venue/exercise-physiology)
    * [ Room Hire ](/venue/room-hire)
    * [ Timetables ](/venue/timetables)
    * [ FAQs ](/venue/faqs)
    * [ About Us ](/venue/about-us)
    * [ Your Membership App ](/venue/active-world)
Close 

  * Join

    * [ Member Benefits ](/join/member-benefits)
    * [ Memberships at Loftus ](/join/loftus-memberships)
    * [ Claim Your Free Trial ](/join/1-day-free-trial)
Close 

  * Contact Us

    * [ Customer Service Charter ](/contact-us/customer-service-charter)
    * [ Get in Touch ](/contact-us/get-in-touch)
    * [ Getting to Loftus Recreation Centre ](/contact-us/location)
    * [ Employment ](/contact-us/employment)
    * [ Manage My Membership ](/contact-us/manage-membership)
    * [ Membership Enquiry ](/contact-us/membership-enquiry)
Close 

  * Search 

Search

Search 




  * [ ](/)
  * Sports
  * Inclusive Activities 



# Inclusive Activities

## 

### Inclusive Activities at Loftus

Loftus Recreation centre is an inclusive facility in which everyone is welcome. Every person has the right to join into the gym, any Group Fitness Class or sporting activity.

### TripAdvisor Panel

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut quis fermentum dolor, in mollis lacus. Morbi pulvinar sem tortor, aliquet suscipit erat sollicitudin sed. Nulla ultricies convallis ipsum, ac semper sapien sollicitudin non. Vestibulum lobortis turpis purus, sed rutrum dolor mattis in. Aenean dapibus pellentesque nisi in convallis. Nulla a sapien tincidunt, convallis nunc vitae, iaculis lectus. Integer pellentesque venenatis pellentesque. Quisque vel pellentesque diam. In accumsan accumsan risus et porta. Aliquam a quam ut enim facilisis gravida. Aenean finibus metus justo, scelerisque euismod metus semper vitae. Phasellus non risus libero.

  * [About Us](/footer-links/about-us)
  * [Customer Service Charter](/footer-links/customer-service-charter)
  * [Inclusive Activities](/footer-links/inclusive-activities)
  * [FAQs](/footer-links/faqs)
  * [Employment](/footer-links/employment)
  * [Memberships](/footer-links/memberships)
  * [Blog/News](/footer-links/blog-news)
  * [Events](/footer-links/events)
  * [Privacy Policy](/footer-links/privacy-policy)



###  Contact us 

  * 99 Loftus Street, Leederville - 6007 
  * 08 9227 6526 


  * [ ](https://www.instagram.com/loftusrec)
  * [ ](https://www.facebook.com/LoftusRec)
  * [ ](https://www.youtube.com/channel/UC4MKxP96QCfcxfyBWCsc33A)



[ ](https://www.belgraviafoundation.org.au/our-purpose) [ ](http://www.companioncard.org.au/)

[Proudly managed by Belgravia Leisure](https://belgravialeisure.com.au)


---

## Page 10: https://www.loftusrecreationcentre.com.au/join/member-benefits

[](/)

[ 08 9227 6526 ](tel:08 9227 6526)

[ Membership ](https://www.loftusrecreationcentre.com.au:443/join/loftus-memberships) [ Free Trial ](https://www.loftusrecreationcentre.com.au:443/join/1-day-free-trial)

  * Junior

    * [ School Holiday Program ](/junior/school-holiday-activities)
Close 

  * Train

    * [ Reformer Pilates ](/train/reformer-pilates-\(1\))
    * [ B Active Functional Training ](/train/b-active-functional-training)
    * [ Memberships at Loftus ](/train/memberships-passes)
    * [ Fitness Facilities ](/train/fitness-facilities)
    * [ BEGIN Program ](/train/begin-program)
    * [ Personal Training ](/train/personal-training)
    * [ Group Exercise Classes ](/train/group-fitness-classes)
    * [ Timetables ](/train/timetables)
    * [ MyZone ](/train/myzone)
    * [ Seniors Exercise Program ](/train/sep)
    * [ Take Charge! Program ](/train/take-charge-program)
    * [ Member Benefits ](/train/member-benefits)
Close 

  * Sports

    * [ Social Sport Competitions ](/play/competitions)
    * [ Basketball ](/play/basketball)
    * [ Netball ](/play/netball)
    * [ Indoor and Outdoor Futsal ](/play/futsal)
    * [ Rebound Soccer ](/play/rebound-soccer)
    * [ Volleyball ](/play/volleyball)
    * [ Court Hire ](/play/court-hire)
    * [ Inclusive Activities ](/play/inclusive-activities)
Close 

  * Venue

    * [ News/Blog ](/venue/news-blog)
    * [ What's On ](/venue/whats-on)
    * [ Cafe ](/venue/cafe)
    * [ Telehealth ](/venue/tele-health)
    * [ Physiotherapy ](/venue/exercise-physiology)
    * [ Room Hire ](/venue/room-hire)
    * [ Timetables ](/venue/timetables)
    * [ FAQs ](/venue/faqs)
    * [ About Us ](/venue/about-us)
    * [ Your Membership App ](/venue/active-world)
Close 

  * Join

    * [ Member Benefits ](/join/member-benefits)
    * [ Memberships at Loftus ](/join/loftus-memberships)
    * [ Claim Your Free Trial ](/join/1-day-free-trial)
Close 

  * Contact Us

    * [ Customer Service Charter ](/contact-us/customer-service-charter)
    * [ Get in Touch ](/contact-us/get-in-touch)
    * [ Getting to Loftus Recreation Centre ](/contact-us/location)
    * [ Employment ](/contact-us/employment)
    * [ Manage My Membership ](/contact-us/manage-membership)
    * [ Membership Enquiry ](/contact-us/membership-enquiry)
Close 

  * Search 

Search

Search 




  * [ ](/)
  * Join
  * Member Benefits 



# Member Benefits

## 

## Get Started at Loftus Recreation Centre

Loftus is your go-to sporting and fitness facility for the whole family to enjoy and becoming a member with us has a range of benefits.

### 24/7 Gym Membership Benefits

We understand that it can be a daunting experience when joining a gym but rest assured that you'll be getting the right advice from our fully trained and qualified health professionals. Not only that you'll recieve continued support to ensure you achieve the results that you're after.

When you become a member with us, you're making a commitment to your health and overall well-being. Regular exercise can help reduce the risk of health concerns and diseases. It's also a great way to establish a healthy routine, become a part of a community of like-minded people and make new friends!

  * 24/7 Access: Train in your own time with 24/7 access to the gym.
  * 3 FREE Appointments in our Begin Program with a fully qualified Personal Trainer.
  * Casual Sport Court Use: Members can enjoy casual use of the sports courts at no additional charge when they're available.
  * PLUS, our friends at Applied Motion Physiotherapy, Pilates and Podiatry will provide you with a $20 off your first massage and $10 off each subsequent one. For physiotherapy appointments, you'll receive a gap free initial consultation if you have private health cover, and $10 off each subsequent visit.



### Premier Membership

With a Premier Membership, you get access to all of the above, PLUS:

  * Reformer Pilates Classes [(Timetable)](/getattachment/d20e48c5-d8c8-448f-98e2-10244802b9f7/loftus-reformer-timetable.pdf?lang=en-au)

  * Functional Training Classes [(Timetable)](/getattachment/ddb62311-f3f6-499f-acfb-02ae3f9841bf/b-active-functional-training-launch-timetable.pdf?lang=en-au)




### Become a Loftus Member

When you become a member with us, you're making a commitment to your health and overall well-being. Get started today!

[ Free Trial ](/join/free-trial) [ Join Us ](/join/memberships)

### TripAdvisor Panel

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut quis fermentum dolor, in mollis lacus. Morbi pulvinar sem tortor, aliquet suscipit erat sollicitudin sed. Nulla ultricies convallis ipsum, ac semper sapien sollicitudin non. Vestibulum lobortis turpis purus, sed rutrum dolor mattis in. Aenean dapibus pellentesque nisi in convallis. Nulla a sapien tincidunt, convallis nunc vitae, iaculis lectus. Integer pellentesque venenatis pellentesque. Quisque vel pellentesque diam. In accumsan accumsan risus et porta. Aliquam a quam ut enim facilisis gravida. Aenean finibus metus justo, scelerisque euismod metus semper vitae. Phasellus non risus libero.

  * [About Us](/footer-links/about-us)
  * [Customer Service Charter](/footer-links/customer-service-charter)
  * [Inclusive Activities](/footer-links/inclusive-activities)
  * [FAQs](/footer-links/faqs)
  * [Employment](/footer-links/employment)
  * [Memberships](/footer-links/memberships)
  * [Blog/News](/footer-links/blog-news)
  * [Events](/footer-links/events)
  * [Privacy Policy](/footer-links/privacy-policy)



###  Contact us 

  * 99 Loftus Street, Leederville - 6007 
  * 08 9227 6526 


  * [ ](https://www.instagram.com/loftusrec)
  * [ ](https://www.facebook.com/LoftusRec)
  * [ ](https://www.youtube.com/channel/UC4MKxP96QCfcxfyBWCsc33A)



[ ](https://www.belgraviafoundation.org.au/our-purpose) [ ](http://www.companioncard.org.au/)

[Proudly managed by Belgravia Leisure](https://belgravialeisure.com.au)


---

